### ISSUE TITLE
BibTeX/BibLaTeX rework [CANONICAL]

### ISSUE THREAD

**Issue by larsgw** [citation-js/citation-js#43]
- [x] Property validation (https://github.com/larsgw/citation.js/issues/162)
- [x] Proper distinction between BibTeX & BibLaTeX (https://github.com/larsgw/citation.js/issues/94)
- [x] Full syntax support (https://github.com/larsgw/citation.js/issues/160, https://github.com/larsgw/citation.js/issues/56)
- [x] Full field support (especially for BibLaTeX; https://github.com/larsgw/citation.js/issues/168)
- [x] Proper TeX commands support (see also [astrocite](https://github.com/dsifford/astrocite)'s [diacritics](https://github.com/dsifford/astrocite/blob/ec8fc902d5910df280970464d429b392ed42f58a/packages/astrocite-bibtex/src/constants.ts#L3-L22) and [known commands](https://github.com/dsifford/astrocite/blob/ec8fc902d5910df280970464d429b392ed42f58a/packages/astrocite-bibtex/src/constants.ts#L49-L109))
- [x] Proper distinction on what the JSON representation of BibTeX (**and** Bib.TXT) should be in terms of TeX commands
- [x] An actual parser for BibTeX (and maybe Bib.TXT), so we can get rid of the horror that is [`TokenStack`](https://github.com/citation-js/citation-js/blob/778a4a3933456b951dd670b413394a1dbf44c9bb/packages/core/src/util/stack.js)
- [ ] [optional] Update the JSON representation to also work as a schema

**Comment by larsgw** [comment]
> Proper distinction on what the JSON representation of BibTeX (and Bib.TXT) should be in terms of TeX commands

Because of peculiarities in regarding concatenating strings (specifically, that even concatenated command names are evaluated normally) this distinction is actually already made for us. There are three representations:

  - a BibTeX or Bib.TXT file
  - a JSON representation with, for each entry:
    - a label,
    - a type, and
    - a list of properties, with fields names normalized and values concatenated but **not** evaluated
  - a JSON representation with for each entry the same, but all the values evaluated

In theory only the first representation (the input file) needs to be a public format, the rest could be private. However, in the modular spirit of this program the first of the two JSON representations was chosen as another semi-public format (i.e. a type registered in the Citation.js input parsing system).

**Comment by larsgw** [comment]
Check out `v0.5.0-alpha.10`.
